### PR TITLE
test: Update GitHub Actions and Python versions

### PR DESCRIPTION
**Pull request by miketheman**
Closes #17

### CODE REVIEW

**Comment by miketheman** [comment]
@mmerickel CI failure due to Python versions - I've added another commit to restrict to a lower version of macOS for now.

**Comment by miketheman** [comment]
There's some weird combination of x86 and x64 versions available - is there architecture-specific code that needs to be validated on different architectures?

**Comment by miketheman** [comment]
@mmerickel I've updated the test matrix to remove architecture-specific Python implementations, since the code doesn't appear to care about different CPU architectures.

**Comment by mmerickel** [comment]
@miketheman this is all great, thank you so much for the work!

**Pull request merged**
